# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '1'

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src/ecommerce-backend:/var/www/src/ecommerce-backend
    working_dir: /var/www/src/ecommerce-backend
  
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  node:
    build: 
      context: docker/node
      dockerfile: Dockerfile
    volumes:
      - ./src/ecommerce-frontend:/var/www/src/ecommerce-frontend
    working_dir: /var/www/src/ecommerce-frontend
    tty: true

volumes:
  mysql-volume: